### ISSUE TITLE
Unknown layer: Functional

### ISSUE THREAD

**Issue by WKKO** [LucasNolasco/DeepDFML-NILM#3]
Can you tell me the python, tensorflow and keras version you use. This will prevent me from making this error when I use your trainedweights --- "Unknown layer: Functional"
best wish!
![848565654](https://user-images.githubusercontent.com/102801456/170239320-b0aad962-3e98-4136-ad98-f71ba1e60e27.PNG)

**Comment by LucasNolasco** [comment]
Oh, I'm sorry about this. I really should have stated the versions for each dependency. I updated the README with all this information and added a requirements file to make it easier to install everything.

**Comment by WKKO** [comment]
Thank you very much for your help！
best wish！
